### ISSUE TITLE
Red Hat branded logo

### ISSUE THREAD

**Issue by slrtbtfs** [redhat-developer/vscode-promql#29]
@squat  What is the state here?

**Comment by squat** [comment]
We just got some options from the team this afternoon. Once it's finalized I'll update here :)

**Comment by slrtbtfs** [comment]
@squat Any updates on this?

**Comment by squat** [comment]
Still waiting; there was no final logo sent out. I'll ping the necessary people again :+1:

**Comment by slrtbtfs** [comment]
> Still waiting; there was no final logo sent out. I'll ping the necessary people again

Did any of these pings come back?

**Comment by slrtbtfs** [comment]
Obsolete, due to https://github.com/prometheus-community/community/issues/27.
